# This workflow will build and test using Maven

name: Maven Build and Test

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build and Run Tests
      run: mvn test --batch-mode --fail-at-end
    - name: Publish Test Report
      if: success() || failure()
      uses: scacap/action-surefire-report@v1